version: '2'
services:
  nginx:
    image: nginx:latest
    networks:
      - gores_network
    external_links:
      - sqlserver:sqlserver
    volumes:
      - "./www:/usr/share/nginx/html:ro"
      - "./nginx-nossl.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "80:80"
    links:
      - app:app
    depends_on:
      - app
  app:
    image: gdwebapi/goresdigitalapi:prod

networks:
  gores_network:
    external: true