version: '2'
services:
  revp:
    image: nginx:latest
    volumes:
      - "./www:/usr/share/nginx/html:ro"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./certs:/usr/share/certs:ro"
      - "./auth/registry.password:/etc/nginx/.htpasswd:ro"
    ports:
      - "80:80"
      - "443:443"
    links:
      - registry:registry
      - app:app
    depends_on:
      - app
  app:
    image: app.agrito.id/agritoforadmin:dev
  registry:
    image: registry:2
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - "/root/nginx-root/reg-data:/var/lib/registry:rw"
